import { readFileSync, writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const packagePath = path.join(root, 'package.json');
const lockPath = path.join(root, 'package-lock.json');
const versionPath = path.join(root, 'src', 'version.ts');

/** 3.2.8 -> 3.2.9; 3.2.9 -> 3.3.0 */
export function nextVersion(current) {
  const match = /^(\d+)\.(\d+)\.(\d+)$/.exec(current);
  if (!match) {
    throw new Error(`Invalid semver: ${current}`);
  }

  const major = Number(match[1]);
  const minor = Number(match[2]);
  const patch = Number(match[3]);

  if (patch < 9) {
    return `${major}.${minor}.${patch + 1}`;
  }

  return `${major}.${minor + 1}.0`;
}

export function bumpVersion() {
  const pkg = JSON.parse(readFileSync(packagePath, 'utf8'));
  const previous = pkg.version;
  const updated = nextVersion(previous);

  pkg.version = updated;
  writeFileSync(packagePath, `${JSON.stringify(pkg, null, 2)}\n`, 'utf8');

  try {
    const lock = JSON.parse(readFileSync(lockPath, 'utf8'));
    lock.version = updated;
    if (lock.packages?.['']) {
      lock.packages[''].version = updated;
    }
    writeFileSync(lockPath, `${JSON.stringify(lock, null, 2)}\n`, 'utf8');
  } catch {
    // package-lock may be absent in some environments
  }

  writeFileSync(
    versionPath,
    `/** Auto-generated by scripts/bump-version.mjs — do not edit manually */\nexport const APP_VERSION = '${updated}';\n`,
    'utf8'
  );

  return { previous, updated };
}

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { previous, updated } = bumpVersion();
  console.log(`Version bumped: ${previous} -> ${updated}`);
}
